name: Deploy to Hugging Face Spaces

on:
  # You can enable this to deploy on every push to main
  # push:
  #   branches:
  #     - main  
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "msmalmir"
          git config --global user.email "ms.malmir@gmail.com"

      - name: Force push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://msmalmir:${HF_TOKEN}@huggingface.co/spaces/msmalmir/smart-resume-optimizer
          git push hf main --force